---
# yamllint disable rule:line-length
#
- id: check-utf8-with-unix-style-new-lines
  name: Check if files are encoded in UTF-8 w/o BOM and has Unix style new lines
  description: Prevent wrong encoding files and/or files have non-Unix style new lines from being committed
  entry: check-utf8-with-unix-style-new-lines
  language: python
  types: [text]

- id: check-file-has-some-contents
  name: Check if files have some contents
  description: Prevent empty files being committed
  entry: check-file-has-some-contents
  language: python
  types: [text]

- id: check-file-exists
  name: Check if file exists
  description: Ensure necessary files exist
  entry: check-file-exists
  language: python
  types: [text]
